services:
  - type: web
    name: portfolio
    env: static
    buildCommand: echo "No build required - static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
